### ISSUE TITLE
core.h:44:22: fatal error: settings.h: No such file or directory

### ISSUE THREAD

**Issue by 1371030** [pebri86/esplay-retro-emulation#21]
/Users/admin/esplay-retro-emulation/retro-esp32/main/includes/core.h:44:22: fatal error: settings.h: No such file or directory
 #include "settings.h"
                      ^
compilation terminated.
make[1]: *** [main.o] Error 1
make: *** [component-main-build] Error 2

**Comment by pebri86** [comment]
I haven't update the code base for retro-esp launcher for a long time, so maybe currently won't work with the latest hardware driver / settings at the sdk folder. If you want working with it, please check the sdk folder for driver api.

**Comment by 1371030** [comment]
Thanks!
