### ISSUE TITLE
mkfw error

### ISSUE THREAD

**Issue by 1371030** [pebri86/esplay-retro-emulation#22]
esp-idf 3.3

/Users/admin/esp/esplay-retro-emulation/retro-esp32/main/main.c:1241:15: error: implicit declaration of function 'set_rom_name_settings' [-Werror=implicit-function-declaration]
               set_rom_name_settings(file_to_load);

**Comment by pebri86** [comment]
Hi, the retro-esp code hasn't been update with latest esplay-sdk, if you want to play with it please check the esplay-sdk folder to check the updated api
