### ISSUE TITLE
The built firmware cannot be flashed in: Data length error

### ISSUE THREAD

**Issue by jianjinliao** [pebri86/esplay-retro-emulation#23]
I'm sorry to raise the problem again. I successfully compiled the firmware, but bootloader will display 'data long error' when it is flashed in. How can I solve it? Thank you very much!

**Comment by pebri86** [comment]
The error means the binary to be flashed not fit in the particular partition, please check the binary size and compare with size in the mkrelease.sh mkfw command ( in bytes size )

**Comment by jianjinliao** [comment]
I changed it mkrelease.sh  OK, but there is another problem: partition length alignment error. Is this the problem of data partition table?

**Comment by pebri86** [comment]
Yes, there's problem with the partition table. The partition table must be 64 byte align. This partition table created automatically by mkfw when flashing, so the size length must be 64 bytes align.

**Comment by jianjinliao** [comment]
Thank you very much for your reply. The problem has been solved. I will compile the firmware suitable for me. 
CLOSE ISSUE
