### ISSUE TITLE
NES simulator mapper Incomplete

### ISSUE THREAD

**Issue by jianjinliao** [pebri86/esplay-retro-emulation#24]
Hi pebri,
      When I use it, I find that some NES games can't run, and they crash and restart repeatedly. After querying the data and checking the code, the mapper of the simulator is incomplete. Is there any way to improve it?
Or add a mapper to the emulator.
Thank You.

**Comment by pebri86** [comment]
Hi,
I believe to add a new mapper you need to add entry the code at mapper folder on the nofrendo components. Once you test the new mapper you can pull request so i can add them to the repository.

**Comment by jianjinliao** [comment]
Yes,I'm trying a new mapper, but I haven't succeeded yet
