### ISSUE TITLE
how to add video output

### ISSUE THREAD

**Issue by new-soul** [pebri86/esplay-retro-emulation#31]
I know that there was a module name fabgl can realize the goal.
I found the other device was out via vga.

**Comment by pebri86** [comment]
You should add the video/vga routine then you could change to render frame to video output rather than to lcd, you can use i2s 1 for rendering video while i2s 0 for sound output

**Comment by new-soul** [comment]
> You should add the video/vga routine then you could change to render frame to video output rather than to lcd, you can use i2s 1 for rendering video while i2s 0 for sound output

Is it colorful? I found it was black and white from other website.

**Comment by pebri86** [comment]
> > You should add the video/vga routine then you could change to render frame to video output rather than to lcd, you can use i2s 1 for rendering video while i2s 0 for sound output
> 
> Is it colorful? I found it was black and white from other website.

The implementation is depend on you it could be colorful or b/w it should be possible
