### ISSUE TITLE
possible optimization to avoid psram for gnuboy

### ISSUE THREAD

**Issue by fariouche** [pebri86/esplay-retro-emulation#32]
Hello,

I see that you have 2 modes to load the ROM... one directly from an sdcard file to PSRAM, and the other is directly flashing a partition. (gnuboy)
I don't know if you a using PSRAM elsewhere, but for the case where you load from a partition, do you now that you can avoid to copy to PSRAM and directly mmap the partition? look at esp_partition_mmap() function. Of course, the address will be read-only.

cheers

**Comment by pebri86** [comment]
Yes, it's possible to do that. Also see my other repo of pocketsprite clone, it using esp32 without psram and mmap directly from flash partition

**Comment by fariouche** [comment]
awesome! thanks ;-)
