### ISSUE TITLE
Application fails to start  

### ISSUE THREAD

**Issue by haleyxu** [pebri86/esplay-retro-emulation#36]
Hi, I recently made this fun project, but I'm running into a problem. The base firmware works fine, but when I select esplay-retro-emu. ESPlay will be black screen, reboot. I wonder if this is caused by the difference in Flash space.
Below is my configuration:
ESP32-WOROVER-E 8MB PSRAM + 8MB Flash

serial message：
...
OK: [3] Length=0x119860
write_partition_table: startTableEntry=4, startFlashAddress=0x050000
Booting application.
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
...

**Comment by pebri86** [comment]
Try to compile from source and reconfig according to your esp32 module.

**Comment by haleyxu** [comment]
thanks，I have solved the question



---- Replied Message ----
| From | Fuji ***@***.***> |
| Date | 01/17/2023 10:38 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [pebri86/esplay-retro-emulation] Application fails to start (Issue #36) |

Try to compile from source and reconfig according to your esp32 module.
